### ISSUE TITLE
thank you page

### ISSUE THREAD

**Issue by citti** [OpenText-DMG/ot-echo-child#13]
http://documentum.opentext.com/thank-you/ 
needs to be updated.

**Comment by weatheredwatcher** [comment]
So I formatted the page a bit better, added a redirect and then a link to get to homepage, just in case the redirect is not working.  For some reason, after I changed it from 5 seconds to 10, it's stopped working.  I changed it back to five but it still is not redirecting.  I'll be returning to this later on today.

**Comment by weatheredwatcher** [comment]
fixed.
