### ISSUE TITLE
ECD custom icon font needs to be brought into template

### ISSUE THREAD

**Issue by citti** [OpenText-DMG/ot-echo-child#5]

**Comment by weatheredwatcher** [comment]
@citti Needs to be tested then re-closed!

**Comment by weatheredwatcher** [comment]
@citti You might need to add these as short-codes just like the ones in Avada.  Let me know if you want me to hard code the sc's into the function.php file or if you would rather just have them setup via the short-coder plugin.

**Comment by citti** [comment]
what is the location of the file? Need to update the CSS bit below with the correct location.

@font-face {
  font-family: 'emcleap';
  src:  url('fonts/emcleap.eot?ilnmxz');
  src:  url('fonts/emcleap.eot?ilnmxz#iefix') format('embedded-opentype'),
    url('fonts/emcleap.ttf?ilnmxz') format('truetype'),
    url('fonts/emcleap.woff?ilnmxz') format('woff'),
    url('fonts/emcleap.svg?ilnmxz#emcleap') format('svg');
  font-weight: normal;
  font-style: normal;
}

**Comment by citti** [comment]
Confirmed these are now in place - David also will be updating the wiki with usable icons as they are brought over 
/Steve
