### ISSUE TITLE
Main nav drop down does not always work

### ISSUE THREAD

**Issue by citti** [OpenText-DMG/ot-echo-child#6]
So I have yet to be able to recreate this consistently but there are times I have been noticing when just browsing the site that the main nav drop down does not work. When you hover over a nav item it displays a blank drop down at least from what i can tell... I believe it is a blank drop down vs the nav hiding behind an intro as on a fresh reload it will resolve the issue. Although I have yet to actual recreate this consistently it is random. 

AS you browse the site and notice this please update this thread so we can start to track down what is going on here. 

/Steve

**Comment by weatheredwatcher** [comment]
I've seen this too.  I was on the leap page without any drop downs.  Going to leap/courier had working dropdowns, but going to documentum/communicate they didn't work.  So yeah, odd.

**Comment by citti** [comment]
ok: http://staging2.ot.com/documentum/ (which i am currently updating) is consistently having the issue. Will try to see if i can figure anything out as i am updating the page.

**Comment by citti** [comment]
just got off a call with Pat. He was able to catch something about this. There is a overflow:hidden set on the <li of the navigation that is stopping this from showing. Now I was able to figure out that on a page that works when you Hover over that item you are viewing that a overflow:visible actual overwrites it. So they must be doing something in JS to add that action if there are sub menu items. Not 100% sure. but that looks to be like what is going on... Worse case we can just overright the style on the <li to remove the hidden style... would need to be tested. But that is the latest on this issue. 
/Steve

**Comment by citti** [comment]
This ended up being one of toms scripts that was originally added to every single page. The script now is only used on the pages where we have the forms and those pages are working fine. Closing issue.
